source "https://rubygems.org" do
  gem "down", "~> 5.0"
  gem "http", "~> 4.0"

  gem "aws-sdk-s3"
  gem "slack-ruby-client"
  gem "rainbow"
  gem "timers"
  gem "async-websocket", "~> 0.8.0"
  gem "twitter"
end
