#!/usr/bin/env ruby
#coding:utf-8
require "rubygems"
require "bundler/setup"
require "logger"
require "timers"
require "../lib/logging_base"
Dir.glob(File.join("..", "lib", "**", "*.rb"), &method(:require))

LOGGER = Logger.new(STDOUT) unless defined? LOGGER

timers = Timers::Group.new

#setup downloader to run every 5 seconds
every_five_seconds = timers.now_and_every(5) do
  #download TS files
  puts "Another 5 seconds"
end

# setup Processor.process to run every 10 minutes
every_ten_minutes = timers.now_and_every(600) do

end

loop { timers.wait }
