source "https://rubygems.org" do
  gem "down", "~> 5.0"
  gem "http", "~> 4.0"

  gem "aws-sdk-s3"

  gem "slack-ruby-client"

  gem "sinatra"
  gem "puma"
  gem "sinatra-contrib"

  gem "rainbow"
  gem "twitter"

  group :development do
    gem "rerun"
    gem "yard"
  end
end
